spring:

  application:
    name: t1-java-demo

  datasource:
    url: "jdbc:postgresql://localhost:5432/t1_demo"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    driverClassName: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml

  kafka:
    bootstrap-servers: 192.168.1.35:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: logging-service
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html



#logging:
#  level:
#    ROOT: INFO
#    ru.t1.java.demo.controller.ClientController: DEBUG

t1:
  scan-path: ru.t1.java.demo
